### ISSUE TITLE
Net::FTP does not naturally support writing to a local Tempfile

### ISSUE THREAD

**Issue by La-comadreja** [rubysl/rubysl-net-ftp#1]
We are using Net::FTP to download a file to a Tempfile object rather than a File.  We need to explicitly set the localfile parameter to nil, even when we write to the Tempfile inside the block.  

I propose that passing in a block should also set localfile to nil, for get(), getbinaryfile() and gettextfile().

We should also allow parameter options where localfile is a Tempfile.

**Comment by YorickPeterse** [comment]
This repository is not the place for feature requests, you should submit these to https://bugs.ruby-lang.org/projects/ruby-trunk. This repository instead mirrors (or re-implements) the code from MRI for Rubinius.
