### ISSUE TITLE
Putbinaryfile (on Windows) requires blocksize equal to file size

### ISSUE THREAD

**Issue by MarkDBlackwell** [rubysl/rubysl-net-ftp#2]
Recently, in the process of developing a new program, I invoked `putbinaryfile` (in passive mode) on a large file (about 1.3 megabytes) without specifying its `blocksize` argument. Invariably, the server terminated the transfer about five seconds after its start. (BTW, this approximates the duration in which other FTP clients completely send this entire file—with my setup.)

Much smaller files transferred fine.

Eventually, using a test file of about 63 kilobytes, I discovered that if I specified a `blocksize` identical to the file length (in bytes), it worked. And the transfer failed when the `blocksize` was one byte smaller.

Now, I've added code (in my own program) in order to obtain the file size of every file I want to send, and set the `blocksize` argument to that size (exactly). (Except, for empty files, I need to set it to `1`.)

Since then, I've sent hundreds of files (many of which are approximately 1 or 2 megabytes in size) without experiencing this problem.

Why should I need to set the `blocksize` in this way? It seems undocumented, to say the least.

I'm on Windows 7 — and I'm using an old version of Ruby (for the moment). Nevertheless, (supposedly) this problem may still exist:
```bash
> ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
```

**Comment by robin850** [comment]
Hi @MarkDBlackwell,

Sorry for the late answer but this gem isn't intended to be used with MRI but with Rubinius ; MRI already ship with its own version of the standard library. It may be worth reporting it [upstream](https://bugs.ruby-lang.org/) though if it's not already the case (it may also already be fixed). 

Thanks for reporting this anyway ! :-)

**Comment by MarkDBlackwell** [comment]
Thank you for the redirection. Just now, I reported it upstream as MRI [Bug 13280, Net/ftp: Putbinaryfile (on Windows) requires blocksize equal to file size](https://bugs.ruby-lang.org/issues/13280).

MRI [Feature 5481, Gemifying Ruby standard library](https://bugs.ruby-lang.org/issues/5481) confirms that net/ftp (in MRI's standard library) hasn't yet been gemified.

Presumably, stating that your repositories are intended only for Rubinius, explicitly in your READMEs ([here](https://github.com/rubysl/rubysl/blob/2.0/README.md), [here](https://github.com/rubysl/rubysl-net-ftp/blob/2.0/README.md) and elsewhere), would help fend off similar bug reports, and save some of your group's time. :)

I suppose these statements might include a link to the upstream issue tracking system, if you consider it helpful.

**Comment by robin850** [comment]
@MarkDBlackwell : Thank you very much for reporting this upstream ! ❤️

> Presumably, stating that your repositories are intended only for Rubinius, explicitly in your READMEs would help fend off similar bug reports, and save some of your group's time. :)

Yeah, you're right ! The main repository's README has been updated accordingly.

@brixen : What do you think about that ? We could update all the READMEs to tell users that these gems are Rubinius-only and also use [an issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) to specify it again as people don't always read README and we could add a link to the MRI tracker if this isn't specific to this gem. I can handle that if you don't have time to put into this.
